### ISSUE TITLE
negativeFlag bug

### ISSUE THREAD

**Issue by HosseinAsadi** [anicdh/bip32-dart#11]
Hi

into codes used negativeFlag, In the event that not implement or declare for that !!!!

bip32-1.0.10/lib/src/utils/ecurve.dart:236:74: Error: Getter not found: 'negativeFlag'.
    needsPaddingByte = ((number >> (rawSize - 1) * 8) & negativeFlag) == negativeFlag ? 1 : 0;
   ...................................................................................................... ^^^^^^^^^^^^

**Comment by p3root** [comment]
negativeFlag is implemented - inside the pointycastle library! What are you trying to do?

**Comment by HosseinAsadi** [comment]
import "package:pointycastle/ecc/curves/secp256k1.dart";
import "package:pointycastle/api.dart" show PrivateKeyParameter, PublicKeyParameter;
import 'package:pointycastle/ecc/api.dart' show ECPrivateKey, ECPublicKey, ECSignature, ECPoint;
import "package:pointycastle/signers/ecdsa_signer.dart";
import 'package:pointycastle/macs/hmac.dart';
import "package:pointycastle/digests/sha256.dart";
import 'package:pointycastle/src/utils.dart';


top of ecurve.dart

but None not include negativeFlag!!

**Comment by p3root** [comment]
because the negative flag will be imported with the
`
import 'package:pointycastle/src/utils.dart';
`

**Comment by HosseinAsadi** [comment]
> Hi
> 
> into codes used negativeFlag, In the event that not implement or declare for that !!!!
> 
> bip32-1.0.10/lib/src/utils/ecurve.dart:236:74: Error: Getter not found: 'negativeFlag'.
> needsPaddingByte = ((number >> (rawSize - 1) * 8) & negativeFlag) == negativeFlag ? 1 : 0;
> ...................................................................................................... ^^^^^^^^^^^^

for fix this error use  pointycastle: ^2.0.1

**Comment by p3root** [comment]
Yeah sure, I will downgrade pointycastle for an error you can't explain me?

**Comment by p3root** [comment]
You could provide me a repo where I can reproduce your issue!
