### ISSUE TITLE
NetworkType

### ISSUE THREAD

**Issue by HosseinAsadi** [anicdh/bip32-dart#13]
why don't work NetworkType

into codes used NetworkType that can as argument gave to this code 'bip32.BIP32.fromSeed(seed)' and with not giving this argument, bitcoin network is default but at all no matter and dont work!!!

**Comment by HosseinAsadi** [comment]
> why don't work NetworkType
> 
> into codes used NetworkType that can as argument gave to this code 'bip32.BIP32.fromSeed(seed)' and with not giving this argument, bitcoin network is default but at all no matter and dont work!!!

you can test this issue with mnemonic and check with https://iancoleman.io/bip39/

**Comment by p3root** [comment]
bro - i use the library in a project with a different network than bitcoin - it works as expected! Please don't create an issue for everything that is working as expected!

**Comment by p3root** [comment]
Or at least describe the issue so that anybody knows what you trying to do and what the issue is about!

**Comment by HosseinAsadi** [comment]
> bro - i use the library in a project with a different network than bitcoin - it works as expected! Please don't create an issue for everything that is working as expected!

bro - you can go to https://iancoleman.io/bip39/ and see private key this mnemonic: "alert cave donor jewel insane recycle dilemma slab swift half diesel liquid" 
output ==> L5Pe6s3hDEpLtHx7hhvL1fJDvVUYPHy5Sgxg2Cudu6kk6Fj2qCnD

 that different with return output from package( for bitcoin)
 
 final seed = bip39.mnemonicToSeed(mnemonic);
  final root = bip32.BIP32.fromSeed(seed);
final node = root.derivePath("m/44'/0'/0'/0/$addressIndex");
print(HEX.encode(node.privateKey));

output ==> f3ceadd2a108e796a5b77f1af0dac9b9060ec04830acbb41242b8a5ca95e0339

**Comment by p3root** [comment]
as you can see in the fixtures.json we use the provides test vectors from the bip32 (https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki).

All test pass, therefore you may have an issue somewhere else. Please check the docs again and asks politly for help!

**Comment by HosseinAsadi** [comment]
> as you can see in the fixtures.json we use the provides test vectors from the bip32 (https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki).
> 
> All test pass, therefore you may have an issue somewhere else. Please check the docs again and asks politly for help!

You could test the above and understand what I mean

anyway Listen Enjoy :)
https://musicdel.ir/single-tracks/10723/

**Comment by p3root** [comment]
Sorry, but I have also a lot of work todo where I get paid. I'm happy to help if you find an issue within the lib. But I can't teach you how to use the lib or fix your bugs. 

Cheers p3,
PS.: I'm more into this kinda stuff ;) 
https://www.youtube.com/watch?v=yPXa56gQlEw

**Comment by HosseinAsadi** [comment]
anyway thank you and video was funny :))
