### ISSUE TITLE
Publish the latest updates on pub.dev

### ISSUE THREAD

**Issue by marcotradenet** [anicdh/bip32-dart#4]
Hello, would it be possible to publish on pub.dev the changes made with this pr https://github.com/dart-bitcoin/bip32-dart/pull/3?     
We have developed a package based on these libraries, but the address derivation is wrong because there is no pull request fix.
Thanks

**Comment by enricotal70** [comment]
Please , pretty please @andoanwkm  and @longhoangwkm  We the Bip32-dart community  would be forever gratefull  if you could publish the last updates on pub.dev,  there are many many projects using you awesome work waiting for this ; )
Enrico

**Comment by longhoangwkm** [comment]
Ops !, we thought we published it, thanks for the reminder

**Comment by longhoangwkm** [comment]
I just published it. You can check it here: https://pub.dev/packages/bip32

Note: [bip32_dart](https://pub.dev/packages/bip32_dart) is an old fork repo which is created by someone else not us
